on:
  workflow_dispatch: {}
  push: {}
  pull_request:
    branches:
     - main
env:
  UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  Token: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  lint-and-test:
    runs-on: self-hosted
    steps:
      - name: Download repository
        uses: github/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true
      - name: Install linter
        run: |
          if [ ! -f ~/go/bin/golangci-lint ]; then
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          fi
      - name: Download libraries
        run: go mod download && go mod tidy
      - name: Lint Go code
        run: ~/go/bin/golangci-lint run ./...

  build-and-push:
    needs: lint-and-test
    if: github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Auth in Docker hub
        run: echo "${{ env.Token }}" | docker login -u "${{ env.UserName }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go-code:latest .
      - name: Push image in Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/go-code:latest
  deploy:
    needs: build-and-push
    if: github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Deploy image
        run: kubectl rollout restart deployment/go-deployment
